import streamlit as st
from utils.ollama_client import OllamaClient

def run_flashcard_app(client, model: str, language: str):
    """Run the flashcard application with the selected model and language."""
    
    # Store model and client in session state for access in other functions
    st.session_state.current_model = model
    st.session_state.current_client = client
    
    # Initialize session state
    if "flashcard_words" not in st.session_state:
        st.session_state.flashcard_words = []
    if "current_word_index" not in st.session_state:
        st.session_state.current_word_index = 0
    if "score" not in st.session_state:
        st.session_state.score = 0
    if "game_started" not in st.session_state:
        st.session_state.game_started = False
    if "show_result" not in st.session_state:
        st.session_state.show_result = False
    if "user_answer" not in st.session_state:
        st.session_state.user_answer = ""
    
    # Display title
    st.title(f"Flash Cards - {language}")
    st.caption(f"Using model: {model}")
    
    # Game setup
    if not st.session_state.game_started:
        st.write("### Select number of words to practice:")
        
        col1, col2, col3 = st.columns(3)
        with col1:
            if st.button("5 Words", type="primary", use_container_width=True):
                start_game(5, client, model, language)
        with col2:
            if st.button("10 Words", type="primary", use_container_width=True):
                start_game(10, client, model, language)
        with col3:
            if st.button("25 Words", type="primary", use_container_width=True):
                start_game(25, client, model, language)
    
    # Game in progress
    else:
        # Check if game is complete
        if st.session_state.current_word_index >= len(st.session_state.flashcard_words):
            show_final_score()
        else:
            show_current_word()

def start_game(word_count: int, client, model: str, language: str):
    """Initialize a new game with the specified number of words."""
    
    with st.spinner(f"Generating {word_count} unique {language} words..."):
        result = client.generate_flashcard_words(model, language, word_count)
    
    if result and result.get("words") and not result.get("error"):
        st.session_state.flashcard_words = result["words"]
        st.session_state.word_source = result.get("source", "unknown")
        st.session_state.debug_info = result.get("debug", "")
        st.session_state.categories = result.get("categories", [])
        st.session_state.current_word_index = 0
        st.session_state.score = 0
        st.session_state.game_started = True
        st.session_state.show_result = False
        st.session_state.user_answer = ""
        st.rerun()
    else:
        # Show detailed error information
        st.error("❌ Failed to generate vocabulary words")
        
        if result:
            with st.expander("🔍 Error Details", expanded=True):
                st.write("**Debug Info:**", result.get("debug", "Unknown error"))
                if result.get("raw_response"):
                    st.write("**Raw Response:**")
                    st.code(result.get("raw_response", "No response"))
                if result.get("attempted_parse"):
                    st.write("**What we tried to parse:**")
                    st.code(result.get("attempted_parse", "No content"))
                    
        st.info("💡 **Troubleshooting Tips:**")
        st.write("1. Ensure your model supports JSON generation")
        st.write("2. Try a different model (some models work better with structured output)")
        st.write("3. Check your API connection and credentials")
        
        if st.button("🔄 Try Again", type="primary"):
            st.rerun()

def show_current_word():
    """Display the current word and handle user input."""
    words = st.session_state.flashcard_words
    current_index = st.session_state.current_word_index
    current_word = words[current_index]
    
    # Progress indicator
    progress = (current_index + 1) / len(words)
    st.progress(progress)
    st.write(f"**Word {current_index + 1} of {len(words)}**")
    
    # Show debug info
    if current_index == 0:  # Only show on first word
        source = st.session_state.get("word_source", "unknown")
        debug_info = st.session_state.get("debug_info", "")
        categories = st.session_state.get("categories", [])
        
        if source == "generated":
            st.success(f"✅ Words dynamically generated by {st.session_state.current_model}")
            if categories:
                st.info(f"📚 Focus categories: {', '.join(categories)}")
        
        with st.expander("🔍 Generation Details"):
            st.write("**Status:**", source)
            st.write("**Info:**", debug_info)
            
            # Show the actual words that were generated
            st.write("**Generated words:**")
            word_list = [f"{i+1}. {w['word']} ({w['part_of_speech']}) = {w['translation']}" 
                        for i, w in enumerate(words[:5])]  # Show first 5 words
            for word_item in word_list:
                st.write(word_item)
            if len(words) > 5:
                st.write(f"... and {len(words) - 5} more words")
    
    # Display the word
    st.markdown("---")
    col1, col2 = st.columns([2, 1])
    
    with col1:
        st.markdown(f"### {current_word['word']}")
    with col2:
        st.markdown(f"*({current_word['part_of_speech']})*")
    
    # User input
    if not st.session_state.show_result:
        user_answer = st.text_input(
            "Enter the English translation:",
            key=f"answer_{current_index}",
            value=st.session_state.user_answer
        )
        
        col1, col2 = st.columns([1, 4])
        with col1:
            if st.button("Submit", type="primary", disabled=not user_answer):
                check_answer(user_answer, current_word['translation'])
    else:
        # Show result
        if st.session_state.last_answer_correct:
            st.success("✅ Correct!")
        else:
            st.error(f"❌ Incorrect. The correct answer is: **{current_word['translation']}**")
        
        if st.button("Next Word", type="primary"):
            st.session_state.current_word_index += 1
            st.session_state.show_result = False
            st.session_state.user_answer = ""
            st.rerun()
    
    # Option to quit
    st.markdown("---")
    if st.button("Quit Game", type="secondary"):
        reset_game()

def check_answer(user_answer: str, correct_answer: str):
    """Check if the user's answer is correct."""
    # Normalize answers for comparison
    user_answer = user_answer.strip().lower()
    correct_answer = correct_answer.strip().lower()
    
    # Check for exact match or common variations
    is_correct = False
    if user_answer == correct_answer:
        is_correct = True
    elif correct_answer.startswith("to ") and user_answer == correct_answer[3:]:
        # Handle infinitive verbs (e.g., "to eat" vs "eat")
        is_correct = True
    elif user_answer.startswith("to ") and user_answer[3:] == correct_answer:
        # Handle infinitive verbs (reverse case)
        is_correct = True
    
    if is_correct:
        st.session_state.score += 1
        st.session_state.last_answer_correct = True
    else:
        st.session_state.last_answer_correct = False
    
    st.session_state.show_result = True
    st.rerun()

def show_final_score():
    """Display the final score and options to play again."""
    total_words = len(st.session_state.flashcard_words)
    score = st.session_state.score
    percentage = (score / total_words) * 100
    
    st.balloons()
    st.markdown("## 🎉 Game Complete!")
    
    # Score display
    col1, col2, col3 = st.columns([1, 2, 1])
    with col2:
        st.metric("Final Score", f"{score}/{total_words}", f"{percentage:.0f}%")
    
    # Feedback message
    if percentage >= 80:
        st.success("Excellent work! You're mastering this vocabulary! 🌟")
    elif percentage >= 60:
        st.info("Good job! Keep practicing to improve further. 💪")
    else:
        st.warning("Keep practicing! You'll get better with time. 📚")
    
    # Play again button
    if st.button("Play Again", type="primary"):
        reset_game()

def reset_game():
    """Reset the game state."""
    st.session_state.flashcard_words = []
    st.session_state.current_word_index = 0
    st.session_state.score = 0
    st.session_state.game_started = False
    st.session_state.show_result = False
    st.session_state.user_answer = ""
    st.rerun()